import 'settings_service.dart';

/// שירות ניהול תרגומים ומחרוזות
class LocalizationService {
  static final LocalizationService _instance = LocalizationService._();
  static LocalizationService get instance => _instance;
  
  LocalizationService._();

  /// האם השפה הנוכחית היא עברית
  bool get isHebrew => SettingsService.instance.locale == 'he';

  /// מחזיר את המחרוזת המתאימה לפי השפה
  String get(String key) {
    if (isHebrew) {
      return _hebrewStrings[key] ?? key;
    } else {
      return _englishStrings[key] ?? key;
    }
  }

  // --- מילון עברית ---
  static const Map<String, String> _hebrewStrings = {
    // כללי
    'app_name': 'The Hunter',
    'app_description': 'חפש כל קובץ במכשיר שלך',
    'or': 'או',
    'continue_google': 'המשך עם Google',
    'continue_guest': 'המשך כאורח',
    'terms_agreement': 'בהתחברות אתה מסכים לתנאי השימוש ומדיניות הפרטיות',
    'share_text': 'שותף מ-The Hunter: \${file.name}',
    'last_backup': 'גיבוי אחרון: \${date}',
    'tap_to_backup': 'לחץ לגיבוי',
    'restore_info': '\${count} קבצים • \${size}',
    'backup_success': 'גובו \${count} קבצים בהצלחה!',
    'backup_error': 'שגיאה בגיבוי',
    'restore_title': 'שחזור מגיבוי',
    'restore_confirm': 'פעולה זו תחליף את כל הנתונים הנוכחיים בנתונים מהגיבוי.\n\nהאם להמשיך?',
    'restore_action': 'שחזר',
    'restore_success': 'שוחזרו \${count} קבצים בהצלחה!',
    'restore_error': 'שגיאה בשחזור',
    'last_backup_title': 'גיבוי אחרון',
    'coming_soon': '\${feature} - בקרוב!',
    'upgrade_success': 'החשבון שודרג בהצלחה!',
    'upgrade_error': 'שגיאה בשדרוג',
    'choose_language': 'בחר שפה',
    'hebrew': 'עברית',
    'english': 'English',
    'app_description_long': 'הכלי האולטימטיבי לחיפוש קבצים מקומיים ביעילות.',
    'folder_downloads': 'הורדות',
    'folder_downloads_desc': 'קבצים שהורדת',
    'folder_camera': 'מצלמה',
    'folder_camera_desc': 'תמונות וסרטונים מהמצלמה',
    'folder_pictures': 'תמונות',
    'folder_pictures_desc': 'תמונות מאפליקציות',
    'folder_documents': 'מסמכים',
    'folder_documents_desc': 'מסמכים ו-PDF',
    'folder_whatsapp': 'WhatsApp',
    'folder_whatsapp_desc': 'מדיה מוואטסאפ',
    'folder_telegram': 'טלגרם',
    'folder_telegram_desc': 'קבצים מטלגרם',
    'folder_screenshots': 'Screenshots',
    'folder_screenshots_desc': 'צילומי מסך',
    'scan_folders_title': 'תיקיות לסריקה',
    'settings_saved': 'ההגדרות נשמרו',
    'scan_folders_explanation': 'בחר אילו תיקיות לסרוק. תיקיות נוספות = יותר קבצים לחיפוש.',
    'folders_selected': '\${count} תיקיות נבחרו',
    'clear': 'נקה',
    'delete_selected': 'מחק נבחרים',
    'finding_duplicates': 'איתור קבצים כפולים',
    'duplicates_found_groups': 'נמצאו \${count} קבוצות',
    'wasted_space': 'מקום מבוזבז: \${size}',
    'scanning': 'סורק...',
    'scan_duplicates': 'סרוק כפולים',
    'no_duplicates_found': 'לא נמצאו קבצים כפולים!',
    'files_clean_desc': 'הקבצים שלך מסודרים ונקיים',
    'identical_files': '\${count} קבצים זהים',
    'wasted': 'מבוזבז: \${size}',
    'original': 'מקור',
    'show_in_folder': 'הצג בתיקייה',
    'loading_files': 'טוען קבצים...',
    'no_files_in_db': 'לא נמצאו קבצים בבסיס הנתונים',
    'identifying_duplicates': 'מזהה כפולים...',
    'checking_progress': 'בודק \${current} מתוך \${total}...',
    'potential_groups_found': 'נמצאו \${count} קבוצות פוטנציאליות...',
    'duplicate_groups_found': 'נמצאו \${count} קבוצות כפולים',
    'no_duplicates': 'לא נמצאו קבצים כפולים',
    'delete_duplicates_title': 'מחיקת קבצים כפולים',
    'delete_duplicates_confirm': 'האם אתה בטוח שברצונך למחוק \${count} קבצים?\n\nפעולה זו בלתי הפיכה!',
    'delete_duplicates_result': 'נמחקו \${deleted} קבצים (\${size})\${failed}',
    'setup_pin': 'הגדר קוד PIN',
    'setup_pin_desc': 'בחר קוד בן 4 ספרות לאבטחת הקבצים שלך',
    'set_pin_button': 'הגדר PIN',
    'enter_pin': 'הזן קוד PIN',
    'secured_files_count': '\${count} קבצים מאובטחים',
    'unlock': 'פתח',
    'lock': 'נעל',
    'folder_empty': 'התיקייה ריקה',
    'add_files_hint': 'הוסף קבצים מתוצאות החיפוש',
    'restore_original': 'שחזר למיקום מקורי',
    'pin_length_error': 'הקוד חייב להיות בן 4 ספרות',
    'pin_setup_error': 'שגיאה בהגדרת הקוד',
    'pin_incorrect': 'קוד שגוי',
    'open_error_short': 'לא ניתן לפתוח את הקובץ',
    'restore_file_title': 'שחזור קובץ',
    'restore_file_confirm': 'האם לשחזר את "\${name}" למיקום המקורי?',
    'restore': 'שחזר',
    'restore_success_short': 'הקובץ שוחזר בהצלחה',
    'restore_error_short': 'שגיאה בשחזור הקובץ',
    'delete_secure_file_confirm': 'האם למחוק את "\${name}" לצמיתות?\n\nפעולה זו בלתי הפיכה!',
    'file_deleted': 'הקובץ נמחק',
    'delete_error_short': 'שגיאה במחיקה',
    'cloud_storage_title': 'אחסון בענן',
    'cloud_storage_subtitle': '\${count} קבצים • \${size}',
    'uploading_progress': 'מעלה... \${percent}%',
    'no_files_cloud': 'אין קבצים בענן',
    'upload_files_hint': 'העלה קבצים מתוצאות החיפוש',
    'download': 'הורד',
    'share_link': 'שתף קישור',
    'access_storage_error': 'לא ניתן לגשת לאחסון',
    'download_complete_title': 'הורדה הושלמה',
    'download_complete_content': 'האם לפתוח את הקובץ?',
    'create_link_error': 'לא ניתן ליצור קישור',
    'delete_cloud_file_confirm': 'האם למחוק את "\${name}" מהענן?\n\nפעולה זו בלתי הפיכה!',
    'benefit_smart_search': 'Smart AI Search',
    'benefit_smart_search_desc': 'חיפוש חכם עם בינה מלאכותית',
    'benefit_voice_search': 'Voice Search',
    'benefit_voice_search_desc': 'חיפוש קולי בעברית ואנגלית',
    'benefit_history': 'Unlimited History',
    'benefit_history_desc': 'היסטוריית חיפושים ללא הגבלה',
    'benefit_support': 'Priority Support',
    'benefit_support_desc': 'תמיכה מועדפת 24/7',
    'benefit_no_ads': 'No Ads',
    'benefit_no_ads_desc': 'ללא פרסומות',
    'dev_mode_active': 'מצב פיתוח פעיל',
    'dev_mode_badge': 'DEV MODE',
    'dev_mode_desc': 'DEV MODE: No real charges will be made. This is a simulated purchase flow for testing.',
    'subscription_disclaimer': 'Payment will be charged to your Google Play account. Subscription automatically renews unless canceled at least 24 hours before the end of the current period.',
    'google_account_required': 'נדרש חשבון Google',
    'google_account_required_desc': 'כדי לרכוש מנוי Pro ולשמור עליו, עליך לקשר את החשבון לחשבון Google.\n\nפעולה זו תבטיח שהמנוי יישמר גם אם תסיר את האפליקציה.',
    'link_account': 'קשר חשבון',
    'link_account_error': 'שגיאה בקישור החשבון',
    'already_subscribed': 'You already have an active subscription!',
    'purchase_success': '🎉 Purchase Successful! Welcome to Pro',
    'purchase_error': 'שגיאה ברכישה: \$error',
    'restore_subscription_success': '✨ Pro subscription restored!',
    'no_subscription_found': 'No active subscription found',
    'restore_error_with_details': 'שגיאה בשחזור: \$error',
    'close': 'סגור',
    'cancel': 'ביטול',
    'confirm': 'אישור',
    'save': 'שמור',
    'delete': 'מחק',
    'open': 'פתח',
    'share': 'שתף',
    'details': 'פרטים',
    'yes': 'כן',
    'no': 'לא',
    'loading': 'טוען...',
    
    // חיפוש
    'search_title': 'חיפוש',
    'search_hint': 'חפש קבצים, תמונות, מסמכים...',
    'filter_all': 'הכל',
    'filter_images': 'תמונות',
    'filter_docs': 'מסמכים',
    'filter_video': 'וידאו',
    'filter_audio': 'אודיו',
    'filter_pdf': 'PDF',
    'filter_favorites': 'מועדפים',
    'connect_drive': 'חבר Google Drive',
    'drive_connected': 'מחובר ל-Google Drive בהצלחה!',
    'drive_error': 'שגיאה בחיבור ל-Google Drive',
    'no_results': 'לא נמצאו תוצאות',
    'found_files': 'נמצאו קבצים',
    'ai_search_active': 'מציג תוצאות לפי AI',
    'ai_search_hint': 'חפש בשפה טבעית עם בינה מלאכותית',
    'search_voice_permission': 'נדרשת הרשאת מיקרופון לחיפוש קולי',
    'search_voice_not_available': 'זיהוי קולי אינו זמין במכשיר זה',
    'search_voice_hint': 'חיפוש קולי (לחיצה ארוכה להחלפת שפה)',
    'search_voice_stop': 'הפסק הקלטה',
    'search_voice_premium': 'חיפוש קולי (פרימיום)',
    'search_language_he': 'שפה: עברית',
    'search_language_en': 'Language: English',
    'delete_files_title': 'מחיקת קבצים',
    'delete_multiple_confirm': 'האם למחוק \$selectedCount קבצים?\nפעולה זו בלתי הפיכה.',
    'delete_multiple_success': 'נמחקו \$deleted קבצים',
    'delete_multiple_partial': 'נמחקו \$deleted קבצים, \$failed נכשלו',
    'share_error': 'שגיאה בשיתוף: \$e',
    'refresh_complete': 'התוצאות עודכנו',
    'file_not_found': 'הקובץ לא נמצא: \${file.name}',
    'remove_from_list': 'הסר',
    'open_error': 'לא ניתן לפתוח את הקובץ: \${result.message}',
    'file_already_deleted': 'הקובץ כבר נמחק מהמכשיר',
    'file_deleted_success': 'הקובץ "\${file.name}" נמחק בהצלחה',
    'delete_error_details': 'שגיאה במחיקת הקובץ: \$e',
    'delete_file_title': 'מחיקת קובץ',
    'delete_file_confirm': 'האם אתה בטוח שברצונך למחוק את הקובץ?',
    'delete_irreversible': 'פעולה זו לא ניתנת לביטול!',
    'file_details_title': 'פרטי קובץ',
    'detail_name': 'שם',
    'detail_type': 'סוג',
    'detail_size': 'גודל',
    'detail_date': 'תאריך שינוי',
    'detail_path': 'נתיב',
    'detail_extracted_text': 'טקסט מחולץ',
    'detail_chars': 'תוווים',
    'action_open': 'פתח',
    'action_open_subtitle': 'פתח עם אפליקציה מתאימה',
    'action_share': 'שתף',
    'action_share_subtitle': 'שלח לאפליקציה אחרת',
    'action_details': 'פרטים',
    'action_details_subtitle': 'הצג מידע על הקובץ',
    'action_delete': 'מחק',
    'action_delete_subtitle': 'מחק את הקובץ לצמיתות',
    'premium_feature_favorites': 'מועדפים',
    'favorite_added': 'נוסף למועדפים',
    'favorite_removed': 'הוסר מהמועדפים',
    'action_add_favorite': 'הוסף למועדפים',
    'action_remove_favorite': 'הסר מהמועדפים',
    'premium_feature_tags': 'תגיות',
    'action_tags_title': 'תגיות',
    'action_tags_subtitle': 'הוסף תגיות לארגון קבצים',
    'tags_dialog_title': 'בחר תגיות',
    'tags_new_button': 'חדשה',
    'tags_new_dialog_title': 'תגית חדשה',
    'tags_name_label': 'שם התגית',
    'tags_name_hint': 'לדוגמה: מסמכים',
    'tags_color_label': 'בחר צבע:',
    'tags_create_button': 'צור',
    'premium_feature_secure': 'תיקייה מאובטחת',
    'action_secure_title': 'העבר לתיקייה מאובטחת',
    'action_secure_subtitle': 'הסתר קובץ מאחורי קוד PIN',
    'secure_move_title': 'העברה לתיקייה מאובטחת',
    'secure_move_confirm': 'האם להעביר את "\${file.name}" לתיקייה המאובטחת?\n\nהקובץ יוסר מהחיפוש הרגיל.',
    'secure_move_button': 'העבר',
    'secure_move_success': 'הקובץ הועבר לתיקייה המאובטחת',
    'secure_move_error': 'שגיאה בהעברת הקובץ',
    'premium_feature_cloud': 'אחסון בענן',
    'action_cloud_title': 'העלה לענן',
    'action_cloud_subtitle': 'שמור העתק בענן לגישה מכל מקום',
    'cloud_upload_login_required': 'יש להתחבר לחשבון כדי להעלות לענן',
    'cloud_upload_title': 'מעלה לענן',
    'cloud_upload_progress': 'מעלה...',
    'cloud_upload_success': 'הקובץ הועלה בהצלחה',
    'cloud_upload_error': 'שגיאה בהעלאה',
    'date_range_all': 'כל הזמנים',
    'smart_search_hint': 'הקלד לפחות 2 תווים לחיפוש חכם',
    'smart_search_result': 'חיפוש חכם: \${intent.terms.join(", ")}',
    'smart_search_no_intent': 'לא הצלחתי להבין את החיפוש, נסה ניסוח אחר',
    'smart_search_error': 'שגיאה בחיפוש חכם: \$e',
    'premium_feature_smart_search': 'חיפוש AI חכם',
    'smart_search_active': 'חיפוש חכם פעיל',
    'smart_search_banner_title': 'חיפוש AI חכם',
    'smart_search_banner_subtitle': 'חפש בשפה טבעית עם בינה מלאכותית',
    'search_header_title': 'חיפוש',
    'filter_chip_all': 'הכל',
    'filter_chip_images': 'תמונות',
    'filter_chip_docs': 'מסמכים',
    'filter_chip_video': 'וידאו',
    'filter_chip_audio': 'אודיו',
    'filter_chip_pdf': 'PDF',
    'results_count': '\${results.length} תוצאות',
    'sort_date': 'ממוין לפי תאריך',
    'empty_state_title_start': 'מתחילים!',
    'empty_state_title_search': 'מה מחפשים?',
    'empty_state_desc_search': 'נסה מילים אחרות או בדוק את האיות',
    'empty_state_desc_scanning': 'הקבצים שלך נסרקים ברקע...',
    'empty_state_desc_start': 'חפש בשפה טבעית - "קבלה מאתמול", "תמונות מהחופשה"',
    'tips_title': 'טיפים',
    'tip_1': 'נסה מילה באנגלית או בעברית',
    'tip_2': 'חפש חלק משם הקובץ',
    'tip_3': 'הסר את הפילטר הנוכחי',
    'stats_ready': '\$dbCount קבצים מוכנים לחיפוש',
    'suggestions_title': 'נסה לחפש:',
    'suggestion_invoice': 'חשבונית',
    'suggestion_id': 'תעודת זהות',
    'suggestion_contract': 'חוזה',
    'recent_files_title': 'נפתחו לאחרונה',
    'time_now': 'עכשיו',
    'selection_count': '\${_selectedFiles.length} נבחרו',
    'select_all': 'בחר הכל',
    'recent_searches_title': 'חיפושים אחרונים',
    'cancel_smart_search': 'ביטול',
    
    // הגדרות
    'settings_title': 'הגדרות',
    'section_backup': 'גיבוי ושחזור',
    'section_general': 'כללי',
    'section_scan': 'סריקה',
    'section_tools': 'כלים',
    'section_about': 'אודות',
    'backup_cloud': 'גיבוי לענן',
    'restore_cloud': 'שחזור מהענן',
    'auto_backup': 'גיבוי אוטומטי',
    'auto_backup_subtitle': 'פעיל - כל 24 שעות',
    'auto_backup_off': 'כבוי',
    'language': 'שפה',
    'theme': 'מצב תצוגה',
    'theme_dark': 'כהה',
    'theme_light': 'בהיר',
    'theme_system': 'מערכת',
    'scan_folders': 'תיקיות לסריקה',
    'scan_folders_subtitle': 'לחץ לבחירת תיקיות',
    'duplicates_finder': 'מחפש כפולים',
    'duplicates_subtitle': 'מצא ומחק קבצים כפולים לפינוי מקום',
    'secure_folder': 'תיקייה מאובטחת',
    'secure_folder_subtitle': 'הסתר קבצים רגישים מאחורי קוד PIN',
    'about_app': 'אודות האפליקציה',
    'logout': 'התנתק',
    'logout_dialog_title': 'התנתקות',
    'logout_dialog_content': 'האם אתה בטוח שברצונך להתנתק?',
    'guest': 'אורח',
    'upgrade_to_google': 'שדרג לחשבון Google',
    'pro_badge': 'PRO',
    'upgrade_premium': 'שדרג לפרימיום',
    
    // פעולות קובץ
    'action_favorite_add': 'הוסף למועדפים',
    'action_favorite_remove': 'הסר מהמועדפים',
    'action_secure_move': 'העבר לתיקייה מאובטחת',
    'action_tags': 'ניהול תגיות',
    'msg_favorite_added': 'נוסף למועדפים',
    'msg_favorite_removed': 'הוסר מהמועדפים',
    'delete_confirm_title': 'מחיקת קובץ',
    'delete_confirm_content': 'האם אתה בטוח שברצונך למחוק את הקובץ?',
    'delete_success': 'הקובץ נמחק בהצלחה',
    'delete_error': 'שגיאה במחיקת הקובץ',
    
    // מנוי
    'subscribe_title': 'Hunter Pro',
    'subscribe_subtitle': 'שדרג כדי לפתוח את כל האפשרויות',
    'plan_monthly': 'חודשי',
    'plan_yearly': 'שנתי',
    'restore_purchases': 'שחזור רכישות',
    'subscribe_now': 'הירשם עכשיו',
    'premium_required': 'נדרש מנוי פרימיום',
    'feature_locked': 'אפשרות זו זמינה למנויי Pro בלבד',
  };

  // --- מילון אנגלית ---
  static const Map<String, String> _englishStrings = {
    // General
    'app_name': 'The Hunter',
    'app_description': 'Search any file on your device',
    'or': 'or',
    'continue_google': 'Continue with Google',
    'continue_guest': 'Continue as Guest',
    'terms_agreement': 'By signing in you agree to Terms of Service and Privacy Policy',
    'share_text': 'Shared from The Hunter: \${file.name}',
    'last_backup': 'Last backup: \${date}',
    'tap_to_backup': 'Tap to backup',
    'restore_info': '\${count} files • \${size}',
    'backup_success': 'Backed up \${count} files successfully!',
    'backup_error': 'Backup error',
    'restore_title': 'Restore from Backup',
    'restore_confirm': 'This action will replace all current data with data from backup.\n\nContinue?',
    'restore_action': 'Restore',
    'restore_success': 'Restored \${count} files successfully!',
    'restore_error': 'Restore error',
    'last_backup_title': 'Last Backup',
    'coming_soon': '\${feature} - Coming Soon!',
    'upgrade_success': 'Account upgraded successfully!',
    'upgrade_error': 'Upgrade error',
    'choose_language': 'Choose Language',
    'hebrew': 'Hebrew',
    'english': 'English',
    'app_description_long': 'The ultimate local file search tool tailored for efficiency.',
    'folder_downloads': 'Downloads',
    'folder_downloads_desc': 'Downloaded files',
    'folder_camera': 'Camera',
    'folder_camera_desc': 'Photos and videos from camera',
    'folder_pictures': 'Pictures',
    'folder_pictures_desc': 'Images from apps',
    'folder_documents': 'Documents',
    'folder_documents_desc': 'Documents and PDFs',
    'folder_whatsapp': 'WhatsApp',
    'folder_whatsapp_desc': 'Media from WhatsApp',
    'folder_telegram': 'Telegram',
    'folder_telegram_desc': 'Files from Telegram',
    'folder_screenshots': 'Screenshots',
    'folder_screenshots_desc': 'Screenshots',
    'scan_folders_title': 'Scan Folders',
    'settings_saved': 'Settings saved',
    'scan_folders_explanation': 'Select folders to scan. More folders = more files to search.',
    'folders_selected': '\${count} folders selected',
    'clear': 'Clear',
    'delete_selected': 'Delete Selected',
    'finding_duplicates': 'Finding Duplicates',
    'duplicates_found_groups': 'Found \${count} groups',
    'wasted_space': 'Wasted space: \${size}',
    'scanning': 'Scanning...',
    'scan_duplicates': 'Scan Duplicates',
    'no_duplicates_found': 'No duplicates found!',
    'files_clean_desc': 'Your files are clean and organized',
    'identical_files': '\${count} identical files',
    'wasted': 'Wasted: \${size}',
    'original': 'Original',
    'show_in_folder': 'Show in folder',
    'loading_files': 'Loading files...',
    'no_files_in_db': 'No files in database',
    'identifying_duplicates': 'Identifying duplicates...',
    'checking_progress': 'Checking \${current} of \${total}...',
    'potential_groups_found': 'Found \${count} potential groups...',
    'duplicate_groups_found': 'Found \${count} duplicate groups',
    'no_duplicates': 'No duplicates found',
    'delete_duplicates_title': 'Delete Duplicates',
    'delete_duplicates_confirm': 'Delete \${count} files?\n\nThis action cannot be undone!',
    'delete_duplicates_result': 'Deleted \${deleted} files (\${size})\${failed}',
    'setup_pin': 'Setup PIN',
    'setup_pin_desc': 'Choose 4-digit code to secure your files',
    'set_pin_button': 'Set PIN',
    'enter_pin': 'Enter PIN',
    'secured_files_count': '\${count} secured files',
    'unlock': 'Unlock',
    'lock': 'Lock',
    'folder_empty': 'Folder is empty',
    'add_files_hint': 'Add files from search results',
    'restore_original': 'Restore to original location',
    'pin_length_error': 'PIN must be 4 digits',
    'pin_setup_error': 'Error setting PIN',
    'pin_incorrect': 'Incorrect PIN',
    'open_error_short': 'Cannot open file',
    'restore_file_title': 'Restore File',
    'restore_file_confirm': 'Restore "\${name}" to original location?',
    'restore': 'Restore',
    'restore_success_short': 'File restored successfully',
    'restore_error_short': 'Error restoring file',
    'delete_secure_file_confirm': 'Delete "\${name}" permanently?\n\nThis action cannot be undone!',
    'file_deleted': 'File deleted',
    'delete_error_short': 'Delete error',
    'cloud_storage_title': 'Cloud Storage',
    'cloud_storage_subtitle': '\${count} files • \${size}',
    'uploading_progress': 'Uploading... \${percent}%',
    'no_files_cloud': 'No files in cloud',
    'upload_files_hint': 'Upload files from search results',
    'download': 'Download',
    'share_link': 'Share Link',
    'access_storage_error': 'Cannot access storage',
    'download_complete_title': 'Download Complete',
    'download_complete_content': 'Open file?',
    'create_link_error': 'Cannot create link',
    'delete_cloud_file_confirm': 'Delete "\${name}" from cloud?\n\nThis action cannot be undone!',
    'subscription_title': 'Hunter Pro',
    'subscription_subtitle': 'Upgrade to unlock all features',
    'plan_monthly': 'Monthly',
    'plan_yearly': 'Yearly',
    'plan_monthly_he': 'Monthly',
    'plan_yearly_he': 'Yearly',
    'restore_purchases': 'Restore Purchases',
    'subscribe_now': 'Subscribe Now',
    'premium_required': 'Premium Required',
    'feature_locked': 'This feature is available for Pro users only',
    'benefit_smart_search': 'Smart AI Search',
    'benefit_smart_search_desc': 'Search naturally with AI',
    'benefit_voice_search': 'Voice Search',
    'benefit_voice_search_desc': 'Voice search in Hebrew & English',
    'benefit_history': 'Unlimited History',
    'benefit_history_desc': 'Unlimited search history',
    'benefit_support': 'Priority Support',
    'benefit_support_desc': '24/7 Priority support',
    'benefit_no_ads': 'No Ads',
    'benefit_no_ads_desc': 'Ad-free experience',
    'dev_mode_active': 'Dev mode active',
    'dev_mode_badge': 'DEV MODE',
    'dev_mode_desc': 'DEV MODE: No real charges will be made. This is a simulated purchase flow for testing.',
    'subscription_disclaimer': 'Payment will be charged to your Google Play account. Subscription automatically renews unless canceled at least 24 hours before the end of the current period.',
    'google_account_required': 'Google Account Required',
    'google_account_required_desc': 'To purchase Pro subscription and keep it, you must link your account to Google.\n\nThis ensures your subscription is saved even if you uninstall the app.',
    'link_account': 'Link Account',
    'link_account_error': 'Error linking account',
    'already_subscribed': 'You already have an active subscription!',
    'purchase_success': '🎉 Purchase Successful! Welcome to Pro',
    'purchase_error': 'Purchase error: \$error',
    'restore_subscription_success': '✨ Pro subscription restored!',
    'no_subscription_found': 'No active subscription found',
    'restore_error_with_details': 'Restore error: \$error',
    'close': 'Close',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'delete': 'Delete',
    'open': 'Open',
    'share': 'Share',
    'details': 'Details',
    'yes': 'Yes',
    'no': 'No',
    'loading': 'Loading...',
    
    // Search
    'search_title': 'Search',
    'search_hint': 'Search files, images, docs...',
    'filter_all': 'All',
    'filter_images': 'Images',
    'filter_docs': 'Documents',
    'filter_video': 'Video',
    'filter_audio': 'Audio',
    'filter_pdf': 'PDF',
    'filter_favorites': 'Favorites',
    'connect_drive': 'Connect Google Drive',
    'drive_connected': 'Connected to Google Drive!',
    'drive_error': 'Error connecting to Google Drive',
    'no_results': 'No results found',
    'found_files': 'files found',
    'ai_search_active': 'Showing AI results',
    'ai_search_hint': 'Search naturally with AI',
    'search_voice_permission': 'Microphone permission required for voice search',
    'search_voice_not_available': 'Voice recognition not available on this device',
    'search_voice_hint': 'Voice search (long press to switch language)',
    'search_voice_stop': 'Stop recording',
    'search_voice_premium': 'Voice search (Premium)',
    'search_language_he': 'שפה: עברית',
    'search_language_en': 'Language: English',
    'delete_files_title': 'Delete Files',
    'delete_multiple_confirm': 'Delete \$selectedCount files?\nThis action cannot be undone.',
    'delete_multiple_success': '\$deleted files deleted',
    'delete_multiple_partial': '\$deleted files deleted, \$failed failed',
    'share_error': 'Error sharing: \$e',
    'refresh_complete': 'Results updated',
    'file_not_found': 'File not found: \${file.name}',
    'remove_from_list': 'Remove',
    'open_error': 'Cannot open file: \${result.message}',
    'file_already_deleted': 'File already deleted from device',
    'file_deleted_success': 'File "\${file.name}" deleted successfully',
    'delete_error_details': 'Error deleting file: \$e',
    'delete_file_title': 'Delete File',
    'delete_file_confirm': 'Are you sure you want to delete this file?',
    'delete_irreversible': 'This action cannot be undone!',
    'file_details_title': 'File Details',
    'detail_name': 'Name',
    'detail_type': 'Type',
    'detail_size': 'Size',
    'detail_date': 'Modified',
    'detail_path': 'Path',
    'detail_extracted_text': 'Extracted Text',
    'detail_chars': 'chars',
    'action_open': 'Open',
    'action_open_subtitle': 'Open with compatible app',
    'action_share': 'Share',
    'action_share_subtitle': 'Send to another app',
    'action_details': 'Details',
    'action_details_subtitle': 'Show file information',
    'action_delete': 'Delete',
    'action_delete_subtitle': 'Delete file permanently',
    'premium_feature_favorites': 'Favorites',
    'favorite_added': 'Added to favorites',
    'favorite_removed': 'Removed from favorites',
    'action_add_favorite': 'Add to Favorites',
    'action_remove_favorite': 'Remove from Favorites',
    'premium_feature_tags': 'Tags',
    'action_tags_title': 'Tags',
    'action_tags_subtitle': 'Add tags to organize files',
    'tags_dialog_title': 'Select Tags',
    'tags_new_button': 'New',
    'tags_new_dialog_title': 'New Tag',
    'tags_name_label': 'Tag Name',
    'tags_name_hint': 'e.g. Documents',
    'tags_color_label': 'Select Color:',
    'tags_create_button': 'Create',
    'premium_feature_secure': 'Secure Folder',
    'action_secure_title': 'Move to Secure Folder',
    'action_secure_subtitle': 'Hide file behind PIN code',
    'secure_move_title': 'Move to Secure Folder',
    'secure_move_confirm': 'Move "\${file.name}" to Secure Folder?\n\nFile will be removed from normal search.',
    'secure_move_button': 'Move',
    'secure_move_success': 'File moved to Secure Folder',
    'secure_move_error': 'Error moving file',
    'premium_feature_cloud': 'Cloud Storage',
    'action_cloud_title': 'Upload to Cloud',
    'action_cloud_subtitle': 'Save copy in cloud for access anywhere',
    'cloud_upload_login_required': 'Login required to upload to cloud',
    'cloud_upload_title': 'Uploading to Cloud',
    'cloud_upload_progress': 'Uploading...',
    'cloud_upload_success': 'File uploaded successfully',
    'cloud_upload_error': 'Upload error',
    'date_range_all': 'All time',
    'smart_search_hint': 'Type at least 2 chars for smart search',
    'smart_search_result': 'Smart Search: \${intent.terms.join(", ")}',
    'smart_search_no_intent': 'Could not understand search, try phrasing differently',
    'smart_search_error': 'Smart search error: \$e',
    'premium_feature_smart_search': 'Smart AI Search',
    'smart_search_active': 'Smart Search Active',
    'smart_search_banner_title': 'Smart AI Search',
    'smart_search_banner_subtitle': 'Search naturally with AI',
    'search_header_title': 'Search',
    'filter_chip_all': 'All',
    'filter_chip_images': 'Images',
    'filter_chip_docs': 'Documents',
    'filter_chip_video': 'Video',
    'filter_chip_audio': 'Audio',
    'filter_chip_pdf': 'PDF',
    'results_count': '\${results.length} results',
    'sort_date': 'Sorted by date',
    'empty_state_title_start': 'Let\'s Start!',
    'empty_state_title_search': 'What are you looking for?',
    'empty_state_desc_search': 'Try other words or check spelling',
    'empty_state_desc_scanning': 'Scanning your files in background...',
    'empty_state_desc_start': 'Search naturally - "Receipt from yesterday", "Vacation photos"',
    'tips_title': 'Tips',
    'tip_1': 'Try English or Hebrew words',
    'tip_2': 'Search part of filename',
    'tip_3': 'Remove current filter',
    'stats_ready': '\$dbCount files ready for search',
    'suggestions_title': 'Try searching:',
    'suggestion_invoice': 'Invoice',
    'suggestion_id': 'ID Card',
    'suggestion_contract': 'Contract',
    'recent_files_title': 'Recently Opened',
    'time_now': 'Now',
    'selection_count': '\${_selectedFiles.length} selected',
    'select_all': 'Select All',
    'recent_searches_title': 'Recent Searches',
    'cancel_smart_search': 'Cancel',
    
    // Settings
    'settings_title': 'Settings',
    'section_backup': 'Backup & Restore',
    'section_general': 'General',
    'section_scan': 'Scanning',
    'section_tools': 'Tools',
    'section_about': 'About',
    'backup_cloud': 'Cloud Backup',
    'restore_cloud': 'Restore from Cloud',
    'auto_backup': 'Auto Backup',
    'auto_backup_subtitle': 'Active - every 24h',
    'auto_backup_off': 'Off',
    'language': 'Language',
    'theme': 'Theme',
    'theme_dark': 'Dark',
    'theme_light': 'Light',
    'theme_system': 'System',
    'scan_folders': 'Scan Folders',
    'scan_folders_subtitle': 'Tap to select folders',
    'duplicates_finder': 'Duplicates Finder',
    'duplicates_subtitle': 'Find and remove duplicate files',
    'secure_folder': 'Secure Folder',
    'secure_folder_subtitle': 'Hide files behind PIN code',
    'about_app': 'About App',
    'logout': 'Logout',
    'logout_dialog_title': 'Logout',
    'logout_dialog_content': 'Are you sure you want to logout?',
    'guest': 'Guest',
    'upgrade_to_google': 'Link Google Account',
    'pro_badge': 'PRO',
    'upgrade_premium': 'Upgrade to Premium',
    
    // File Actions
    'action_favorite_add': 'Add to Favorites',
    'action_favorite_remove': 'Remove from Favorites',
    'action_secure_move': 'Move to Secure Folder',
    'action_tags': 'Manage Tags',
    'msg_favorite_added': 'Added to favorites',
    'msg_favorite_removed': 'Removed from favorites',
    'delete_confirm_title': 'Delete File',
    'delete_confirm_content': 'Are you sure you want to delete this file?',
    'delete_success': 'File deleted successfully',
    'delete_error': 'Error deleting file',
    
  };
}

/// קיצור דרך לשימוש בקוד
String tr(String key) => LocalizationService.instance.get(key);
