// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheHunterApi.Data;

#nullable disable

namespace TheHunterApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205092342_AddSearchActivities")]
    partial class AddSearchActivities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TheHunterApi.Data.UserAiUsage", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("YearMonth")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("ScanCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "YearMonth");

                    b.HasIndex("UserId", "YearMonth");

                    b.ToTable("UserAiUsages");
                });

            modelBuilder.Entity("TheHunterApi.Data.UserLearningQuota", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("DateKey")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("SuggestionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "DateKey");

                    b.HasIndex("UserId", "DateKey");

                    b.ToTable("UserLearningQuotas");
                });

            modelBuilder.Entity("TheHunterApi.Models.LearnedTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Term");

                    b.HasIndex("Term", "Category")
                        .IsUnique();

                    b.ToTable("LearnedTerms");
                });

            modelBuilder.Entity("TheHunterApi.Models.RankingSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Key");

                    b.ToTable("RankingSettings");

                    b.HasData(
                        new
                        {
                            Key = "filenameWeight",
                            Value = 200.0
                        },
                        new
                        {
                            Key = "contentWeight",
                            Value = 120.0
                        },
                        new
                        {
                            Key = "pathWeight",
                            Value = 80.0
                        },
                        new
                        {
                            Key = "fullMatchMultiplier",
                            Value = 1.2
                        },
                        new
                        {
                            Key = "exactPhraseBonus",
                            Value = 150.0
                        });
                });

            modelBuilder.Entity("TheHunterApi.Models.SearchActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSearch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Term")
                        .IsUnique();

                    b.ToTable("SearchActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
