// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheHunterApi.Data;

#nullable disable

namespace TheHunterApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131220925_InitialQuota")]
    partial class InitialQuota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TheHunterApi.Data.UserAiUsage", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("YearMonth")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("ScanCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "YearMonth");

                    b.HasIndex("UserId", "YearMonth");

                    b.ToTable("UserAiUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
